import { useEffect, useState } from "react";
import jsPDF from "jspdf";

const API = import.meta.env.VITE_API_BASE || "";

async function safeJson(res) {
  const ct = res.headers.get("content-type") || "";
  if (ct.includes("application/json")) return res.json();
  const text = await res.text();
  return { error: text || `Non-JSON response (${res.status})` };
}

export default function Attempts() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState("");

  async function load() {
    try {
      setLoading(true);
      const res = await fetch(`${API}/api/attempts`, { credentials: "include" });
      const data = await safeJson(res);

      if (res.status === 401 || res.status === 403) {
        throw new Error("Not logged in / session missing. Pehle login karo.");
      }
      if (!res.ok) throw new Error(data.error || "Failed to load attempts");
      setItems(data.attempts || []);
    } catch (e) {
      alert("Load attempts error: " + e.message);
    } finally {
      setLoading(false);
    }
  }

  async function remove(id) {
    const ok = confirm("Delete this attempt?");
    if (!ok) return;

    try {
      setBusyId(id);
      const res = await fetch(`${API}/api/attempt/${id}`, {
        method: "DELETE",
        credentials: "include",
      });
      const data = await safeJson(res);

      if (res.status === 401 || res.status === 403) {
        throw new Error("Not logged in / session missing. Pehle login karo.");
      }
      if (!res.ok) throw new Error(data.error || "Delete failed");

      setItems((prev) => prev.filter((x) => x._id !== id));
    } catch (e) {
      alert("Delete error: " + e.message);
    } finally {
      setBusyId("");
    }
  }

  function downloadReport(a) {
  const doc = new jsPDF("p", "mm", "a4");

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const date = a.createdAt ? new Date(a.createdAt).toLocaleString() : "N/A";
  const score = Number(a.score ?? 0);

  const status =
    score >= 8 ? "Excellent" :
    score >= 6 ? "Good" :
    score >= 4 ? "Average" :
    "Needs Improvement";

  // Header
  doc.setFillColor(20, 24, 38);
  doc.rect(0, 0, pageWidth, 34, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text("AI Interview Performance Report", margin, 15);

  doc.setFontSize(10);
  doc.text("Generated by AI Interview Platform", margin, 24);

  // Score Card
  doc.setTextColor(20, 24, 38);
  doc.setFillColor(245, 247, 251);
  doc.roundedRect(margin, 42, 182, 35, 4, 4, "F");

  doc.setFontSize(14);
  doc.text("Interview Summary", margin + 5, 53);

  doc.setFontSize(11);
  doc.text(`Date: ${date}`, margin + 5, 62);
  doc.text(`Voice ID: ${a.voiceId || "N/A"}`, margin + 5, 70);

  doc.setFontSize(24);
  doc.text(`${score}/10`, 160, 58);

  doc.setFontSize(11);
  doc.text(status, 160, 68);

  let y = 90;

  function sectionTitle(title) {
    doc.setFillColor(20, 24, 38);
    doc.setTextColor(255, 255, 255);
    doc.roundedRect(margin, y, 182, 9, 2, 2, "F");
    doc.setFontSize(12);
    doc.text(title, margin + 4, y + 6);
    y += 15;
    doc.setTextColor(30, 30, 30);
  }

  function addBox(text) {
    const lines = doc.splitTextToSize(text || "N/A", 172);
    const boxHeight = Math.max(18, lines.length * 6 + 8);

    if (y + boxHeight > 280) {
      doc.addPage();
      y = 20;
    }

    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(220, 225, 235);
    doc.roundedRect(margin, y, 182, boxHeight, 3, 3, "FD");

    doc.setFontSize(10);
    doc.setTextColor(45, 45, 45);
    doc.text(lines, margin + 5, y + 8);

    y += boxHeight + 10;
  }

  sectionTitle("Question");
  addBox(a.question || "N/A");

  sectionTitle("Candidate Answer");
  addBox(a.answerText || "No answer saved");

  sectionTitle("AI Feedback");
  addBox(a.feedback || "No feedback saved");

  sectionTitle("Evaluation Table");

  doc.setFillColor(235, 239, 246);
  doc.setTextColor(20, 24, 38);
  doc.rect(margin, y, 182, 10, "F");

  doc.setFontSize(10);
  doc.text("Metric", margin + 5, y + 7);
  doc.text("Result", margin + 75, y + 7);
  doc.text("Remarks", margin + 125, y + 7);

  y += 10;

  const rows = [
    ["Score", `${score}/10`, status],
    ["Communication", score >= 6 ? "Good" : "Needs Work", "Based on answer clarity"],
    ["Technical Accuracy", score >= 7 ? "Strong" : "Improve", "Based on correctness"],
    ["Interview Readiness", score >= 8 ? "Ready" : "Practice More", "Overall performance"],
  ];

  rows.forEach((row) => {
    doc.setDrawColor(220, 225, 235);
    doc.rect(margin, y, 182, 10);
    doc.text(row[0], margin + 5, y + 7);
    doc.text(row[1], margin + 75, y + 7);
    doc.text(row[2], margin + 125, y + 7);
    y += 10;
  });

  y += 12;

  if (a.what_was_good?.length) {
    sectionTitle("What Was Good");
    addBox(a.what_was_good.map((x) => `• ${x}`).join("\n"));
  }

  if (a.what_to_improve?.length) {
    sectionTitle("What To Improve");
    addBox(a.what_to_improve.map((x) => `• ${x}`).join("\n"));
  }

  if (a.audioUrl) {
    sectionTitle("Recording Link");
    addBox(a.audioUrl);
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(
      `AI Interview Platform | Page ${i} of ${pageCount}`,
      margin,
      290
    );
  }

  doc.save(`AI-Interview-Report-${Date.now()}.pdf`);
}

  useEffect(() => {
    load();
  }, []);

  return (
    <div className="at-wrap">
      <div className="at-card">
        <div className="at-head">
          <h2 style={{ margin: 0 }}>📚 My Attempts</h2>
          <button className="ai-btn" onClick={load} disabled={loading}>
            {loading ? "Loading..." : "Refresh"}
          </button>
        </div>

        <div className="ai-muted" style={{ marginTop: 8 }}>
          API: {API}
        </div>

        {loading ? (
          <div className="ai-muted" style={{ marginTop: 12 }}>Loading...</div>
        ) : items.length === 0 ? (
          <div className="ai-muted" style={{ marginTop: 12 }}>No attempts saved yet.</div>
        ) : (
          <div style={{ marginTop: 12 }}>
            {items.map((a) => (
              <div key={a._id} className="at-item">
                <div className="at-date">
                  {a.createdAt ? new Date(a.createdAt).toLocaleString() : ""}
                </div>

                <div className="at-q">Q: {a.question}</div>

                {a.answerText ? (
                  <div style={{ marginTop: 10 }}>
                    <div className="at-sub">Answer</div>
                    <div style={{ whiteSpace: "pre-wrap" }}>{a.answerText}</div>
                  </div>
                ) : (
                  <div className="at-sub">(No answer text saved)</div>
                )}

                {a.feedback ? (
                  <div style={{ marginTop: 10 }}>
                    <div className="at-sub">Feedback</div>
                    <div style={{ whiteSpace: "pre-wrap" }}>{a.feedback}</div>
                  </div>
                ) : null}

                <div className="at-pillrow">
                  <span className="at-pill">Voice: {a.voiceId || "—"}</span>
                  <span className="at-pill">Score: {a.score ?? "—"}/10</span>
                  
                  <button
  className="ai-btn ai-btn-primary"
  onClick={() => downloadReport(a)}
>

                    Download Report
                  </button>

                  <button
                    className="ai-btn ai-btn-danger"
                    onClick={() => remove(a._id)}
                    disabled={busyId === a._id}
                    title="Delete attempt"
                  >
                    {busyId === a._id ? "Deleting..." : "Delete"}
                  </button>
                </div>

                {a.audioUrl ? (
                  <div style={{ marginTop: 12 }}>
                    <div className="at-sub">Recording</div>
                    <audio controls src={a.audioUrl} className="at-audio" />
                    <div className="at-sub" style={{ marginTop: 6 }}>
                      <a href={a.audioUrl} target="_blank" rel="noreferrer">Open file</a>
                    </div>
                  </div>
                ) : null}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
